export { default as Main } from './main/Main'
export { default as Cotalog } from './caotalog/Cotalog'
export { default as Rest } from './rest/Rest'
export { default as About } from  './about/About'
export { default as Vacansy } from './vacansy/Vacansy'
export { default as LikedProducts }  from './likedProducts/LikedProducts'
export { default as Kazrinka } from './karzinka/Karzinka'